### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by anklee** [fooxy/homeassistant-aqara#10]
17-01-09 12:56:40 homeassistant.bootstrap: Error during setup of component aqara
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/bootstrap.py", line 151, in _async_setup_component
    None, component.setup, hass, config)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/aqara.py", line 36, in setup
    gateway.initGateway()
  File "/home/homeassistant/.homeassistant/deps/pyAqara/gateway.py", line 50, in initGateway
    self.socket = self._prepare_socket()
  File "/home/homeassistant/.homeassistant/deps/pyAqara/gateway.py", line 144, in _prepare_socket
    sock.bind(("0.0.0.0", self.MULTICAST_PORT))
OSError: [Errno 98] Address already in use

**Comment by monster1025** [comment]
Some script on your machine already use port 9898, needed to run aqara gateway. No error in aqara-gateway here.

**Comment by JasonCampey** [comment]
Think there was an earlier post about something like this and apple home
kit using the same port

**Comment by anklee** [comment]
Thank you
I changed port
is ok.

**Comment by erj855** [comment]
我想问下，你的端口是如何修改的

**Comment by anklee** [comment]
修改PY文件，里面有个端口，具体要找找。
/.homeassistant/custom_components/aqara.py
你看看是不是这个文件里面有没有

**Comment by abaozang** [comment]
@anklee I tried to change the port in another file but it just saved for a while. after restarting home assistant it went back to 9898. Could you pls tell me how you did this?

**Comment by anklee** [comment]
@abaozang 
I 'm not at home.
try /home/homeassistant/.homeassistant/deps/pyAqara/gateway.py

**Comment by anklee** [comment]
@abaozang 
@erj855 
see below
https://github.com/fooxy/homeassisitant-pyAqara
setup.py	Fix for UDP port 9898	2 months ago
