### ISSUE TITLE
Seems to be broken on HASS 0.39

### ISSUE THREAD

**Issue by famaia** [fooxy/homeassistant-aqara#14]
Is it me or aqara is now broken on HASS 0.39 ?
Had to revert to 0.38.4...

---

ERROR:homeassistant.loader:Error loading custom_components.aqara. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/loader.py", line 141, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/root/.homeassistant/custom_components/aqara.py", line 1, in <module>
    from homeassistant.components.discovery import load_platform
ImportError: cannot import name 'load_platform'
ERROR:homeassistant.loader:Unable to find component aqara

**Comment by csabyka** [comment]
same as me

**Comment by JasonCampey** [comment]
yep same here.. Same errors as famaia.. Pirt 3.9 has a cool feature I would like to use. 
Looks like the line ImportError: cannot import name 'load_platform' holds the key. One of the  import lines in the aqara script might have to be changed or updated.

**Comment by sofixa** [comment]
Same here, but i've found a fix (i'll submit a PR tomorrow or the weekend):

* modify the [aqara.py](https://github.com/fooxy/homeassistant-aqara/blob/master/custom_components/aqara.py) file to change all occurences of load_platform (there's 2 of them) to async_load_platform
* manually install homeassistant-pyAqara by running:
```
pip3 install https://github.com/fooxy/homeassisitant-pyAqara/archive/v0.45-alpha.zip
```
In the same virtualenv as your HASS installation.

**Comment by JasonCampey** [comment]
Thanks Sofixa.. Have not tried this yet but good to know someone has got it going again

**Comment by famaia** [comment]
Hi, any news, still seems broken?
I've tried sofixa advice, but got stuck anyway.

Actually, I don't understand: If I change the code on .homeassistant/custom_components and then run the pip3 install command, will the local code that I just fixed, be overwritten?
